name: Laminar build & test

on:
  push:
    branches:
    - TimonPost-patch-1
    
jobs:
  linux_mac:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: installing rust
      run: |
        echo Hello world ${HOME}
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        ls ${HOME}/.cargo/bin/
        rustc --version
    - name: building laminar
      run: ${HOME}/.cargo/bin/cargo build --verbose
    - name: testing lamianr
      run: ${HOME}/.cargo/bin/cargo test --verbose    
 

