name: Laminar build & test

on:
  push:
    branches:
    - TimonPost-patch-1
    
jobs:
  test:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: installing rust
      run: |
        curl https://sh.rustup.rs -sSf --output rustup.sh
        sh ./rustup.sh -y    
        ls $HOME/.cargo/bin/
        rustc --version
    - name: building laminar
      run: $HOME/.cargo/bin/cargo build --verbose
    - name: testing lamianr
      run: $HOME/.cargo/bin/cargo test --verbose    
