name: Testing Laminar 

on:
  push:
    branches:
    - TimonPost-patch-1
    
jobs:
  linux_mac:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        rust: [stable]
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run check
      run: cargo check --all
    - name: Run tests
      run: cargo test --all
 

