name: Testing Laminar 

on:
  push:
    branches:
    - TimonPost-patch-1
    
jobs:
  linux_mac:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows_latest]
        rust: [nightly]
    steps:
    - uses: actions/checkout@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run check
      run: cargo check --all
    - name: Run tests
      run: cargo test --all 
 

